FROM plexinc/pms-docker:latest

ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update \
	&& apt-get install -y cifs-utils \
	
	# Cleanup
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && rm -rf /var/tmp/*

COPY root/ /